import numpy as np

from bone import Bone, Muscle
from config import g


def kinetic_energy(bone: Bone) -> float:
    """
    Calculates the kinetic energy of a single bone.
    """
    return 0.5 * bone.J * bone.theta_dot ** 2 + 0.5 * bone.m * float(np.linalg.norm(bone.G_dot) ** 2)


def potential_energy(bone: Bone) -> float:
    """
    Calculates the potential energy of a single bone relative to its initial state.
    """
    return bone.m * g * bone.G[1] - bone.Ep0


def total_kinetic_energy(bones: list[Bone]) -> float:
    """
    Calculates the total kinetic energy of the system.
    """
    return sum(kinetic_energy(bone) for bone in bones)


def total_potential_energy(bones: list[Bone]) -> float:
    """
    Calculates the total potential energy of the system.
    """
    return sum(potential_energy(bone) for bone in bones)


def p_muscle(muscle: Muscle, effort: float) -> float:
    """
    Calculates the power generated by a muscle.
    """
    p = 0.0
    for bone in [muscle.bone0, muscle.bone1]:
        if bone.name != 'ground':
            p += effort * (np.dot(bone.F_max_muscles[muscle.name], bone.G_dot) + bone.C_max_muscles[
                muscle.name] * bone.theta_dot)
    return p


def get_gravity_center(bones: list[Bone]) -> np.ndarray:
    """
    Calculates the center of gravity of the human.
    """
    return 1 / sum([bone.m for bone in bones]) * np.sum(np.array([bone.m * bone.G for bone in bones]), axis=0)
